import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../../context/AppContext';

export default function ExportReportScreen() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { getAssessment, getPatient } = useApp();
  const a = getAssessment(id);
  const patient = getPatient(a?.patientId);
  const [exporting, setExporting] = useState(false);
  const [done, setDone] = useState(false);

  if (!a) return null;

  const riskColor = { Low: '#34D399', Medium: '#FBBF24', High: '#F87171' }[a.riskLevel];

  async function doExport(type) {
    setExporting(true);
    await new Promise(r => setTimeout(r, 1800));
    setExporting(false);
    setDone(true);

    if (type === 'pdf') {
      // Generate printable HTML and open print dialog
      const html = `
        <html><head><title>PediPredict AI Report</title>
        <style>body{font-family:sans-serif;padding:30px;color:#222}h1{color:#F43F5E}table{width:100%;border-collapse:collapse;margin:16px 0}td,th{border:1px solid #ddd;padding:8px;text-align:left}.risk{color:${riskColor};font-weight:bold}</style></head>
        <body>
          <h1>🦷 PediPredict AI – Clinical Report</h1>
          <p><strong>Patient:</strong> ${patient?.name} | <strong>Age:</strong> ${patient?.age} | <strong>Date:</strong> ${a.date}</p>
          <table><tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Anxiety Score</td><td>${a.anxietyScore}%</td></tr>
            <tr><td>Detected Emotion</td><td>${a.emotion}</td></tr>
            <tr><td>Cooperation Level</td><td>${a.cooperationLevel}</td></tr>
            <tr><td>Risk Level</td><td class="risk">${a.riskLevel}</td></tr>
          </table>
          <h2>AI Recommendation</h2><p>${a.recommendation}</p>
          ${a.notes ? `<h2>Dentist Notes</h2><p>${a.notes}</p>` : ''}
          <p style="color:#999;font-size:12px;margin-top:40px">Generated by PediPredict AI · ${new Date().toLocaleDateString()}</p>
        </body></html>`;
      const w = window.open('', '_blank');
      w.document.write(html);
      w.document.close();
      w.print();
    }
  }

  return (
    <div className="screen-centered" style={{ padding: '40px 24px' }}>
      <div className="orb orb-1" />

      <div className="fade-in" style={{ width: '100%', maxWidth: 400 }}>
        <button className="back-btn" onClick={() => navigate(`/history/${id}`)} style={{ marginBottom: 20 }}>← Back</button>

        <h1 style={{ fontSize: 24, fontWeight: 800, marginBottom: 6, textAlign: 'center' }}>Export Report</h1>
        <p style={{ color: '#9E857E', fontSize: 14, textAlign: 'center', marginBottom: 28 }}>Choose how you'd like to export this assessment report</p>

        {!done ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[
              { type: 'pdf', icon: '📄', label: 'Export as PDF', sub: 'Opens print dialog for PDF saving' },
              { type: 'share', icon: '📤', label: 'Share Report', sub: 'Copy shareable summary' },
              { type: 'print', icon: '🖨️', label: 'Print Report', sub: 'Direct print to printer' },
            ].map(opt => (
              <button key={opt.type} className="card" disabled={exporting}
                onClick={() => doExport(opt.type)}
                style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '16px 18px', border: 'none', cursor: 'pointer', fontFamily: 'inherit', textAlign: 'left', width: '100%', transition: 'all 0.2s' }}>
                <span style={{ fontSize: 34 }}>{exporting ? '⏳' : opt.icon}</span>
                <div>
                  <div style={{ fontWeight: 700, color: '#FAF2EC' }}>{opt.label}</div>
                  <div style={{ color: '#9E857E', fontSize: 13 }}>{opt.sub}</div>
                </div>
              </button>
            ))}
          </div>
        ) : (
          <div className="card" style={{ textAlign: 'center', padding: 32 }}>
            <div style={{ fontSize: 60, marginBottom: 12 }}>✅</div>
            <div style={{ fontSize: 18, fontWeight: 800, marginBottom: 6 }}>Export Successful!</div>
            <p style={{ color: '#9E857E', fontSize: 14 }}>Your report has been exported.</p>
            <button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => navigate('/history')}>Back to History</button>
          </div>
        )}
      </div>
    </div>
  );
}
